### ISSUE TITLE
[Windows] cannot install mkl blas using conda 4.9.2

### ISSUE THREAD

**Issue by stanmart** [conda-forge/blas-feedstock#56]
Issue:
Since upgrading to `conda 4.9.2` my previously working environment is broken, and I believe the root of the issue is the `libblas=*=*mkl` requirement. The issue is Windows-only - the following work fine on Linux even with `conda 4.9.2`. To reproduce the issue, just try to create the simplest possible environment:

```
$ conda create --new temp python libblas=*=*mkl

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__win==0=0: 100%|████████████████████████████| 4/4 [00:02<00:00,  1.82it/s]-
failed

UnsatisfiableError:
Note that strict channel priority may have removed packages required for satisfiability.
```

It worked fine a week and a half ago with `conda 4.9.0`, and since this feedstock did not changed during that time, I can only assume that the issue is somehow related to the conda version bump. I don't really understand how it could happen, though, as there does not seem to be any breaking changes from `conda 4.9.0 --> 4.9.2`. Let me know if it is a conda problem instead of a feedstock problem and I will open an issue there.

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : None
       user config file : C:\Users\*****\.condarc
 populated config files : C:\Users\*****\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.6.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\*****\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\*****\Miniconda3\pkgs
                          C:\Users\*****\.conda\pkgs
                          C:\Users\*****\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\*****\Miniconda3\envs
                          C:\Users\*****\.conda\envs
                          C:\Users\*****\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.8.6 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/intel_repack-feedstock/pull/17

**Comment by stanmart** [comment]
Something is still not okay with this. Can it be related to build numbers? The 'libblas' feedstock seems to require a very specific build (256):
```
libblas 3.8.0 20_mkl
--------------------
file name   : libblas-3.8.0-20_mkl.tar.bz2
name        : libblas
version     : 3.8.0
build       : 20_mkl
build number: 20
size        : 3.9 MB
license     : BSD-3-Clause
subdir      : win-64
url         : https://conda.anaconda.org/conda-forge/win-64/libblas-3.8.0-20_mkl.tar.bz2
md5         : d7f366eb6821372e5ee81764af1d5be7
timestamp   : 2020-10-25 05:29:35 UTC
constraints :
  - libcblas 3.8.0 20_mkl
  - liblapack 3.8.0 20_mkl
  - liblapacke 3.8.0 20_mkl
  - blas * mkl
dependencies:
  - mkl >=2020.2,<2021.0a0 256
```

When I look at the available `mkl` packages, a hash-looking string is prepended to the build number of the conda-forge version:
```
 $ conda search mkl=2020.2
Loading channels: done
# Name                       Version           Build  Channel
mkl                           2020.2             256  pkgs/main
mkl                           2020.2    h57928b3_256  conda-forge
```
Is it possible that `mkl-2020.2-h57928b3_256.tar.bz2` does not satisfy the build constraint for `libblas 3.8.0 20_mkl`?

**Comment by isuruf** [comment]
Looks like it. Can you send a PR to update the build number at https://github.com/conda-forge/blas-feedstock/blob/master/recipe/meta.yaml#L2

**Comment by stanmart** [comment]
Sure. Why does bumping that _blas_ build number solve the issue, though? Does it initiate a rebuild and the requirement gets fixed automagically? I don't even see where the build number 256 comes from for the dependency.

**Comment by isuruf** [comment]
Yes and yes. We pin to the exact version/build string that was there at build time, https://github.com/conda-forge/blas-feedstock/blob/master/recipe/meta.yaml#L69

**Comment by stanmart** [comment]
Done (I think). Thanks or the explanation!

**Comment by stanmart** [comment]
Yay, it works now.
